# Assignment Set 3
by Zahraoruji for Deep Learing Course at DataScience Center, SBU

# Create three random tensors

In [31]:
import torch
import numpy as np
import h5py

In [17]:
print(torch.__version__)

1.5.0+cpu


In [18]:
if torch.cuda.is_available():
    print("GPU Supported")
else:
    print("GPU Not Supported")

GPU Not Supported


In [44]:
device = torch.device("cuda:0")
device

device(type='cuda', index=0)

In [67]:
a = torch.randn(3,3, dtype=torch.float,device=torch.device('cpu'))
print(a)
print(a.size())

tensor([[ 0.6975,  1.0072, -0.1742],
        [ 1.3723,  0.4453,  1.2338],
        [-0.3201,  0.9554,  0.9012]])
torch.Size([3, 3])


In [68]:
b = torch.randn(4,4, dtype=torch.double,device=torch.device('cpu'))
print(b)
print(b.size())

tensor([[ 1.1114, -0.8001, -0.0872, -0.0722],
        [ 1.5962,  0.4649,  1.4181, -1.9579],
        [-0.1852, -0.7003,  0.0936,  0.3060],
        [ 0.0346, -0.7378,  0.1696, -0.1747]], dtype=torch.float64)
torch.Size([4, 4])


In [69]:
d = torch.randint(-10,10,(5,3,4), dtype=torch.short,device=torch.device('cpu'))
print(d)
print(d.size())

tensor([[[ -2,   7,  -5,   4],
         [-10,   0,  -8,  -9],
         [  8,   5,  -7,  -6]],

        [[ -4,  -6,   7,   7],
         [  1,   5,  -2,   4],
         [  5,  -5,  -2,   0]],

        [[  4,  -5,   6,   4],
         [  7,  -4,  -5,   5],
         [ -4,   7,   0,   1]],

        [[ -9,  -9,  -7,   1],
         [ -9,  -2,   1,  -1],
         [  4,  -5,   3,   2]],

        [[  1,  -6,   4,  -5],
         [  0,   1,   3,   4],
         [ -9,  -8,   4,   0]]], dtype=torch.int16)
torch.Size([5, 3, 4])


# Change tensor's elements
 Display the order of its elements and its transpose in the memory then use storage offset and contiguous

In [70]:
a= a**3
b= (2*b)+4
d= d-3

In [71]:
a_t=a.t()
a_t

tensor([[ 0.3393,  2.5843, -0.0328],
        [ 1.0218,  0.0883,  0.8722],
        [-0.0053,  1.8784,  0.7318]])

In [72]:
a.is_contiguous()

True

In [73]:
a.storage()

 0.3392784297466278
 1.0217747688293457
 -0.005289955530315638
 2.584341049194336
 0.0883152037858963
 1.8783886432647705
 -0.03278973698616028
 0.8721926212310791
 0.7318373918533325
[torch.FloatStorage of size 9]

In [74]:
a[2].storage_offset()

6

In [75]:
a_t.storage()

 0.3392784297466278
 1.0217747688293457
 -0.005289955530315638
 2.584341049194336
 0.0883152037858963
 1.8783886432647705
 -0.03278973698616028
 0.8721926212310791
 0.7318373918533325
[torch.FloatStorage of size 9]

In [76]:
a_t[2,1].storage_offset()

5

In [77]:
b_t=b.t()
b_t

tensor([[6.2228, 7.1924, 3.6297, 4.0692],
        [2.3999, 4.9298, 2.5995, 2.5244],
        [3.8256, 6.8361, 4.1872, 4.3391],
        [3.8556, 0.0843, 4.6119, 3.6506]], dtype=torch.float64)

In [78]:
b.is_contiguous()

True

In [79]:
b.storage()

 6.222784175446954
 2.3998966919243596
 3.825554166060477
 3.8555514407751055
 7.192376794766689
 4.929793919117548
 6.836137559564502
 0.08428923805360355
 3.6296627723191226
 2.5994917388827052
 4.187152182131989
 4.611927890586502
 4.069247598462094
 2.5244345554267946
 4.3391284385032165
 3.650620733141104
[torch.DoubleStorage of size 16]

In [81]:
b[3].storage_offset()

12

In [82]:
b_t.storage()

 6.222784175446954
 2.3998966919243596
 3.825554166060477
 3.8555514407751055
 7.192376794766689
 4.929793919117548
 6.836137559564502
 0.08428923805360355
 3.6296627723191226
 2.5994917388827052
 4.187152182131989
 4.611927890586502
 4.069247598462094
 2.5244345554267946
 4.3391284385032165
 3.650620733141104
[torch.DoubleStorage of size 16]

In [84]:
b_t[3,1].storage_offset()

7

In [87]:
d_t= d.transpose(0,2)
d_t

tensor([[[ -5,  -7,   1, -12,  -2],
         [-13,  -2,   4, -12,  -3],
         [  5,   2,  -7,   1, -12]],

        [[  4,  -9,  -8, -12,  -9],
         [ -3,   2,  -7,  -5,  -2],
         [  2,  -8,   4,  -8, -11]],

        [[ -8,   4,   3, -10,   1],
         [-11,  -5,  -8,  -2,   0],
         [-10,  -5,  -3,   0,   1]],

        [[  1,   4,   1,  -2,  -8],
         [-12,   1,   2,  -4,   1],
         [ -9,  -3,  -2,  -1,  -3]]], dtype=torch.int16)

In [88]:
d.is_contiguous()

True

In [89]:
d.storage()

 -5
 4
 -8
 1
 -13
 -3
 -11
 -12
 5
 2
 -10
 -9
 -7
 -9
 4
 4
 -2
 2
 -5
 1
 2
 -8
 -5
 -3
 1
 -8
 3
 1
 4
 -7
 -8
 2
 -7
 4
 -3
 -2
 -12
 -12
 -10
 -2
 -12
 -5
 -2
 -4
 1
 -8
 0
 -1
 -2
 -9
 1
 -8
 -3
 -2
 0
 1
 -12
 -11
 1
 -3
[torch.ShortStorage of size 60]

In [91]:
d[3].storage_offset()

36

In [92]:
d_t.storage()

 -5
 4
 -8
 1
 -13
 -3
 -11
 -12
 5
 2
 -10
 -9
 -7
 -9
 4
 4
 -2
 2
 -5
 1
 2
 -8
 -5
 -3
 1
 -8
 3
 1
 4
 -7
 -8
 2
 -7
 4
 -3
 -2
 -12
 -12
 -10
 -2
 -12
 -5
 -2
 -4
 1
 -8
 0
 -1
 -2
 -9
 1
 -8
 -3
 -2
 0
 1
 -12
 -11
 1
 -3
[torch.ShortStorage of size 60]

In [96]:
d_t[3,2].storage_offset()

11

# Save and load tensors

In [97]:
a_np= a.numpy()
a_np

array([[ 0.33927843,  1.0217748 , -0.00528996],
       [ 2.584341  ,  0.0883152 ,  1.8783886 ],
       [-0.03278974,  0.8721926 ,  0.7318374 ]], dtype=float32)

In [101]:
b_np= b.numpy()
b_np

array([[6.22278418, 2.39989669, 3.82555417, 3.85555144],
       [7.19237679, 4.92979392, 6.83613756, 0.08428924],
       [3.62966277, 2.59949174, 4.18715218, 4.61192789],
       [4.0692476 , 2.52443456, 4.33912844, 3.65062073]])

In [102]:
d_np= d.numpy()
d_np

array([[[ -5,   4,  -8,   1],
        [-13,  -3, -11, -12],
        [  5,   2, -10,  -9]],

       [[ -7,  -9,   4,   4],
        [ -2,   2,  -5,   1],
        [  2,  -8,  -5,  -3]],

       [[  1,  -8,   3,   1],
        [  4,  -7,  -8,   2],
        [ -7,   4,  -3,  -2]],

       [[-12, -12, -10,  -2],
        [-12,  -5,  -2,  -4],
        [  1,  -8,   0,  -1]],

       [[ -2,  -9,   1,  -8],
        [ -3,  -2,   0,   1],
        [-12, -11,   1,  -3]]], dtype=int16)

In [103]:
a= torch.from_numpy(a_np)

In [104]:
b= torch.from_numpy(b_np)

In [105]:
d= torch.from_numpy(d_np)

In [106]:
torch.save(a,'adata.t' )
torch.save(b,'bdata.t')
torch.save(d,'ddata.t')

In [109]:
with open('adata.t','wb') as f:
    torch.save(a,f)

In [110]:
with open('bdata.t','wb') as f:
    torch.save(b,f)

In [111]:
with open('ddata.t','wb') as f:
    torch.save(d,f)

In [112]:
a= torch.load('adata.t')

In [113]:
b= torch.load('bdata.t')

In [114]:
d= torch.load('ddata.t')

In [115]:
with open('adata.t','rb') as f:
    a=torch.load(f)

In [116]:
with open('bdata.t','rb') as f:
    b=torch.load(f)

In [122]:
with open('ddata.t','rb') as f:
    d=torch.load(f)

In [126]:
import h5py

f= h5py.File('adata.hdf5' , 'w')
data_set=f.create_dataset('coords', data=a.numpy())

In [124]:
f= h5py.File('bdata.hdf5' , 'w')
data_set=f.create_dataset('coords', data=b.numpy())

In [125]:
f= h5py.File('ddata.hdf5' , 'w')
data_set=f.create_dataset('coords', data=d.numpy())

In [127]:
f= h5py.File('adata.hdf5' , 'r')
data_set=f['coords']

In [128]:
f= h5py.File('bdata.hdf5' , 'r')
data_set=f['coords']

In [129]:
f= h5py.File('ddata.hdf5' , 'r')
data_set=f['coords']

# Autograd by the backward method

In [135]:
a=torch.randn((3,3))

In [136]:
b=torch.randn((3,3),requires_grad=True)

In [137]:
S=a+b
S

tensor([[ 0.1219, -0.8763,  0.9151],
        [-1.3503, -0.8935,  0.1727],
        [-0.7985, -1.1002, -1.5914]], grad_fn=<AddBackward0>)

In [138]:
a.requires_grad

False

In [139]:
P=2*a + 3*b
P

tensor([[ 0.2685, -1.1304,  2.1472],
        [-3.1727, -1.4783,  1.3286],
        [-0.4656, -4.3856, -3.4959]], grad_fn=<AddBackward0>)

In [140]:
b.requires_grad

True