In [1]:
import numpy as np

In [2]:
# Defining activations
def sigmoid(x):
  y=1/(1 + np.exp(-x))
  return y
def tanh(x):
  y=np.tanh(x)
  return y
def relu(x):
  if x<0:
    return 0
  else:
    return x

In [3]:
# A class for a layer
class layer:   
  def __init__(self, input_dim, out_dim, activation):
    self.input_dim=input_dim
    self.out_dim=out_dim   
    self.w=[[np.random.randn() for i in range(self.input_dim)] for j in range(self.out_dim)]
    self.b=[np.random.randn() for i in range(self.out_dim)]
    if activation=='sigmoid':
      self.activation=sigmoid
    elif activation=='tanh':
      self.activation=tanh
    elif activation=='relu':
      self.activation=relu
    else:
      print('The activation argument is not valid for this layer. Tanh is selected as default')
      self.activation=tanh    
  def forward(self, input):
    output=[]
    for i in range(self.out_dim):
      neuron_input=0
      for j in range(self.input_dim):
        neuron_input += input[j]*self.w[i][j]
      neuron_input += self.b[i]
      output.append(self.activation(neuron_input))
    return np.array(output)

In [4]:
# A class for Neural Network
class NN:
  def __init__(self, layers_dimensions, activations):
    self.layers_dimensions=layers_dimensions
    self.activations=activations
    self.layers=[]
    for i in range (len(layers_dimensions)-1): # I assumed to have layers_dimensions[0] as input dimension 
      self.layers.append(layer(layers_dimensions[i],layers_dimensions[i+1],activations[i]))
  def forward_pass(self, input):
    hidden_state=input
    for i in range (len(self.layers)):
      hidden_state=self.layers[i].forward(hidden_state)
    return hidden_state 

In [5]:
# Testing activations
print(sigmoid(-1),tanh(-1),relu(-1))

0.2689414213699951 -0.7615941559557649 0


In [6]:
# Testing layer class
test_layer=layer(10,30,'i')
input1=np.random.randn(10)
test_layer.forward(input1)

The activation argument is not valid for this layer. Tanh is selected as default


array([ 0.81237633, -0.99755527,  0.99978102, -0.99999217, -0.98956293,
        0.81627324,  0.17548029,  0.81404987, -0.48864242,  0.9994619 ,
        0.99999841, -0.9999378 ,  0.9876283 , -0.95909656, -0.8674587 ,
       -0.95939752, -0.81242342,  0.89787464, -0.99966699, -0.94961506,
       -0.99989638, -0.999995  , -0.97918611,  0.8056575 , -0.99469209,
       -0.95011171,  0.999998  , -0.99750007, -0.98165647, -0.98990963])

In [7]:
print(test_layer.w[29],'\n',test_layer.b[29])

[0.7815733401777468, 0.37008154657671377, 0.08544365024565807, 0.04292962558638935, -0.08788405686168385, 0.9600778480969017, -0.4481015080485241, 0.8523508374068819, 1.1503928291667729, 1.433433094615398] 
 -0.26009645038937584


In [8]:
test_layer.b[29]=100
test_layer.forward(input1)


array([ 0.81237633, -0.99755527,  0.99978102, -0.99999217, -0.98956293,
        0.81627324,  0.17548029,  0.81404987, -0.48864242,  0.9994619 ,
        0.99999841, -0.9999378 ,  0.9876283 , -0.95909656, -0.8674587 ,
       -0.95939752, -0.81242342,  0.89787464, -0.99966699, -0.94961506,
       -0.99989638, -0.999995  , -0.97918611,  0.8056575 , -0.99469209,
       -0.95011171,  0.999998  , -0.99750007, -0.98165647,  1.        ])

In [9]:
# Testing neural network class
test_net=NN([5,10,15,20],['s','sigmoid','e'])

The activation argument is not valid for this layer. Tanh is selected as default
The activation argument is not valid for this layer. Tanh is selected as default


In [10]:
len(test_net.layers)

3

In [11]:
test_net.layers[1].w[1]

[-2.342716675700261,
 -0.567324898147866,
 2.046132156371193,
 -0.1588963939700445,
 -0.8985459975221752,
 -0.11447614776236689,
 0.14288898394123295,
 -2.270046987624003,
 0.4853219302479302,
 0.3545077462626905]

In [12]:
input2=np.random.randn(10)
input2
test_net.forward_pass(input2)

array([-0.99928397, -0.21761274,  0.99380241, -0.98532724, -0.99985002,
        0.15658224,  0.80565478, -0.97395707, -0.71935005, -0.95288538,
        0.11641608,  0.01124661,  0.98313825, -0.92282043,  0.99999857,
       -0.97885275, -0.9298802 ,  0.94802987,  0.99815941,  0.99999922])

In [13]:
test_net.layers[2].b[19]=100
test_net.layers[2].b[19]

100

In [14]:
test_net.forward_pass(input2)

array([-0.99928397, -0.21761274,  0.99380241, -0.98532724, -0.99985002,
        0.15658224,  0.80565478, -0.97395707, -0.71935005, -0.95288538,
        0.11641608,  0.01124661,  0.98313825, -0.92282043,  0.99999857,
       -0.97885275, -0.9298802 ,  0.94802987,  0.99815941,  1.        ])

In [15]:
test_net.layers[2].w[18][14]=-1000
test_net.layers[2].w[18][14]

-1000

In [16]:
test_net.forward_pass(input2)

array([-0.99928397, -0.21761274,  0.99380241, -0.98532724, -0.99985002,
        0.15658224,  0.80565478, -0.97395707, -0.71935005, -0.95288538,
        0.11641608,  0.01124661,  0.98313825, -0.92282043,  0.99999857,
       -0.97885275, -0.9298802 ,  0.94802987, -1.        ,  1.        ])

In [17]:
test_net.layers[0].w[9][4]=-1000
test_net.layers[0].w[9][4]

-1000

In [18]:
test_net.forward_pass(input2)

array([-0.99930449, -0.26676483,  0.99371796, -0.98511023, -0.99987051,
        0.16127382,  0.80287796, -0.97925283, -0.74463802, -0.95468417,
        0.2133701 ,  0.00892214,  0.98268101, -0.90284978,  0.99999859,
       -0.97438637, -0.92909706,  0.93244979, -1.        ,  1.        ])

In [19]:
test_layers=np.random.randint(10, high=100, size=201)
print(test_layers)
test_activations= ['tanh' for i in range(200)]
test_deep_net=NN(test_layers,test_activations)
print('\n',len(test_deep_net.layers),'\n')
test_deep_net.forward_pass(np.random.randn(test_layers[0]))

[23 58 75 32 66 59 54 75 41 94 87 24 88 87 74 80 68 15 58 19 70 39 82 78
 87 72 13 36 15 10 31 71 82 23 22 44 74 59 52 23 26 62 46 80 24 97 17 71
 55 14 23 80 50 86 88 42 34 73 95 18 61 94 40 87 95 16 60 37 98 67 45 92
 53 26 60 63 47 66 91 16 96 79 40 51 63 71 80 57 98 87 40 59 44 10 67 83
 90 24 14 53 64 85 26 36 52 50 39 65 10 34 80 52 54 63 82 52 44 81 98 60
 93 59 61 75 74 52 89 50 99 58 67 17 24 17 79 89 22 57 64 47 28 15 78 44
 23 34 78 51 37 64 50 33 94 74 83 79 62 99 31 52 94 88 37 83 83 78 81 89
 72 66 70 21 99 28 70 79 10 38 21 62 93 19 86 33 26 65 44 38 90 57 10 51
 97 27 94 57 22 35 80 33 65]

 200 



array([-0.99657301,  0.80488743, -0.99988648, -0.99999674,  0.95027357,
        1.        , -1.        ,  0.79356458,  0.99996495, -1.        ,
        0.99996455, -0.34400801, -0.99999999, -0.99999524,  0.87325889,
        0.96406255,  0.49552371,  0.99968561,  0.99421736, -0.99791981,
       -0.99989938, -0.99987545, -0.999736  ,  0.99342776, -0.67808552,
        0.99965026,  0.99999988,  0.99925895,  0.87966464,  1.        ,
        0.99789924,  0.99999555, -0.90634239, -0.99999977,  0.99909134,
        0.9999958 ,  0.99999429,  0.91457282,  0.08796705,  0.99999958,
       -0.56916935, -0.12142966,  0.99996891,  0.99988555, -0.99999987,
       -0.88246421,  0.20125054,  0.99869651,  0.93584334,  0.97201088,
       -0.68177168, -0.99057847,  0.99999434,  0.79401085, -0.97994828,
       -0.99256487, -0.99984967,  0.99937469, -0.92364935, -1.        ,
        0.9855895 , -0.30151311,  0.99982884, -0.99999531,  0.99999939])

In [20]:
test_layers=np.random.randint(10, high=100, size=51)
print(test_layers)
test_activations= ['tanh' for i in range(50)]
test_deep_net=NN(test_layers,test_activations)
print('\n',len(test_deep_net.layers),'\n')
test_deep_net.forward_pass(np.random.randn(test_layers[0]))

[32 44 17 13 97 16 72 14 90 38 81 89 20 55 73 56 91 30 84 76 74 24 13 16
 41 46 94 89 49 90 71 86 79 21 90 61 84 22 90 13 56 36 19 73 75 82 38 63
 79 63 32]

 50 



array([-1.        ,  0.99999879,  1.        ,  0.99989838,  1.        ,
        0.75276082, -0.88704213, -0.99987549,  0.99999998,  0.99999979,
       -0.99999872, -1.        , -0.99904891,  0.98399826,  0.99985719,
        1.        , -0.99999599, -0.9999966 ,  0.99996549, -0.99984788,
        0.99736432, -0.99999951,  0.71981843,  1.        , -0.99360626,
       -1.        , -0.99996895, -0.99738361,  1.        ,  0.7906767 ,
       -0.53788028, -0.62340219])